version: 0.2

phases:
  build:
    commands:
      - echo "Preparing Lambda deployment packages..."
      - cd backend/get-products
      - zip -r ../../get-products.zip .
      - cd ../create-order
      - zip -r ../../create-order.zip .
      - cd ../order-processor
      - zip -r ../../order-processor.zip .

artifacts:
  files:
    - get-products.zip

  secondary-artifacts:
    BuildGetProducts:
      files:
        - get-products.zip

    BuildCreateOrder:
      files:
        - create-order.zip

    BuildOrderProcessor:
      files:
        - order-processor.zip
