version: 0.2

phases:
  build:
    commands:
      - echo "Preparing Lambda deployment packages..."

      - cd backend/get-products
      - zip -r ../../get-products.zip lambda_function.py
      - cd ../create-order
      - zip -r ../../create-order.zip lambda_function.py
      - cd ../order-processor
      - zip -r ../../order-processor.zip lambda_function.py

artifacts:
  files:
    - get-products.zip
    - create-order.zip
    - order-processor.zip
